### ISSUE TITLE
missing icons on waybar

### ISSUE THREAD

**Issue by trxlezi** [avnibilgin/dotfiles#1]
missing speaker/bluetooth/firefox/file manager icons on waybar, can you pls help me?

**Comment by avnibilgin** [comment]
Hi,

the icons are nerd fonts. I used various nerd fonts. You need to download
the fonts to your system via your software manager or directly. I just
added the following folders to my Github: .icon .themes .local/share/fonts/ All
the things you need should be there. The required fonts are in the
local/share/fonts folder. If you have the fonts on your computer, the nerd
fonts will be displayed correctly in the bar (in the form of icons).

Am Do., 1. Feb. 2024 um 03:31 Uhr schrieb trxlezi ***@***.***

**Comment by avnibilgin** [comment]
Unfortunately, as a precaution, I had to remove the fonts, icons, and
themes from my Github site for legal reasons. But I created a list in the
readme file of which fonts etc. I used. You can download the fonts using
your package manager. The most important are Jetbrain fonts and symbol nerd
fonts. But I think I used nerd icons from a different font from the list
every now and then, so it's better to download all the icons on the list.

Am Do., 1. Feb. 2024 um 03:31 Uhr schrieb trxlezi ***@***.***
