### ISSUE TITLE
Missing reference file from /.cache folder

### ISSUE THREAD

**Issue by regul4rj0hn** [avnibilgin/dotfiles#2]
Thanks for sharing your dots, much appreciated.

Just wanted to point out in case that you were not aware, that some of your configs (e.g. `~/.config/waybar/style.css`) import an external file from `../../.cache/wal/colors-waybar.css` that's not available on your dots, so then lines like this one break styles:
```css
@define-color use_wrk_fg @color5;
``` 

Danke schön!

**Comment by regul4rj0hn** [comment]
Nevermind, I had an out-of-date version locally, I see that you added it. My apologies!

**Comment by avnibilgin** [comment]
No problem, others pointed it out to me before them and I added it later.
Thanks...

Am Fr., 2. Feb. 2024 um 15:33 Uhr schrieb Mauro Lavigna <
***@***.***>:
